import {
  FaBed,
  FaCouch,
  FaUsers,
  FaSwimmingPool,
  GiMeal,
  FaMusic,
  FaWifi,
  FaTv,
  FaBlog,
  MdOutlineNoMeals,
  MdNoMeals,
} from "react-icons/fa";
import {
  Home,
  User,
  Settings,
  Mail,
  Bell,
  Star,
  Check,
  AlertCircle,
  Calendar,
  Coffee,
  Music,
  Camera,
  Heart,
  Film,
  UtensilsCrossed,
} from "lucide-react";

export const carouselContent = [
  [
    {
      id: 1,
      icon: FaBed,
      title: "6 Master Bedrooms",
      description: "Air conditioned with an attached balcony",
    },
    {
      id: 2,
      icon: FaCouch,
      title: "Spacious Living Room",
      description: "Sofa Set | Dining Area | Fully Air Conditioned",
    },
    {
      id: 3,
      icon: FaUsers,
      title: "25-30 guests",
      description: "Suitable for family, friends and corporate getaways",
    },
    {
      id: 4,
      icon: FaSwimmingPool,
      title: "Private Swimming Pool",
      description:
        "Full size | Waterfall | Patio loungers | Underwater LED Lighting",
    },
    {
      id: 5,
      icon: UtensilsCrossed,
      title: "Meals",
      description:
        "Vegetarian | Non-Vegetarian | Jain Meal Plan (Breakfast, Lunch, High Tea, Dinner) ",
    },
    {
      id: 6,
      icon: FaMusic,
      title: "Music System",
      description: "Bluetooth, USB & AUX connectivity | Karaoke",
    },
    {
      id: 7,
      icon: FaWifi,
      title: "High-Speed WiFi",
      description: "Speed upto 30 MBPS",
    },
    {
      id: 8,
      icon: FaTv,
      title: "Smart Television",
      description: "Full HD 50 inch LED",
    },
    {
      id: 9,
      icon: FaBlog,
      title: "Online Streaming",
      description: "Netflix | Disney + Hotstar | Amazon Prime",
    },
  ],
  [
    { id: 10, icon: Home, title: "Barbeque 2", description: "Outdoor BBQ fun" },
    {
      id: 11,
      icon: User,
      title: "Sheesha 2",
      description: "Relax with Sheesha",
    },
    {
      id: 12,
      icon: Settings,
      title: "Bonfire 2",
      description: "Enjoy a cozy bonfire",
    },
    {
      id: 13,
      icon: Mail,
      title: "Packaged Drinking Water 2",
      description: "Complimentary",
    },
    {
      id: 14,
      icon: Bell,
      title: "Concierge and Housekeeping Staff 2",
      description: "Professional, highly trained & experienced",
    },
    {
      id: 15,
      icon: Star,
      title: "Mini-Library 2",
      description: "Fiction, Biography, Children, Fantasy",
    },
    {
      id: 16,
      icon: Check,
      title: "Indoor Activities 2",
      description: "Carrom, Chess, UNO, Jenga, Scrabble, Monopoly",
    },
    {
      id: 17,
      icon: AlertCircle,
      title: "Outdoor Sports 2",
      description: "Cricket Kit, Badminton Set, Football",
    },
    {
      id: 18,
      icon: Calendar,
      title: "Mocktails on arrival 2",
      description: "Piña Colada, Mojito, Blue Curaçao",
    },
  ],
  [
    { id: 19, icon: Home, title: "Barbeque 3", description: "Outdoor BBQ fun" },
    {
      id: 20,
      icon: User,
      title: "Sheesha 3",
      description: "Relax with Sheesha",
    },
    {
      id: 21,
      icon: Settings,
      title: "Bonfire 3",
      description: "Enjoy a cozy bonfire",
    },
    {
      id: 22,
      icon: Mail,
      title: "Packaged Drinking Water 3",
      description: "Complimentary",
    },
    {
      id: 23,
      icon: Bell,
      title: "Concierge and Housekeeping Staff 3",
      description: "Professional, highly trained & experienced",
    },
    {
      id: 24,
      icon: Star,
      title: "Mini-Library 3",
      description: "Fiction, Biography, Children, Fantasy",
    },
    {
      id: 25,
      icon: Check,
      title: "Indoor Activities 3",
      description: "Carrom, Chess, UNO, Jenga, Scrabble, Monopoly",
    },
    {
      id: 26,
      icon: AlertCircle,
      title: "Outdoor Sports 3",
      description: "Cricket Kit, Badminton Set, Football",
    },
    {
      id: 27,
      icon: Calendar,
      title: "Mocktails on arrival 3",
      description: "Piña Colada, Mojito, Blue Curaçao",
    },
  ],
  [
    {
      id: 28,
      icon: Coffee,
      title: "Coffee",
      description: "Freshly brewed coffee",
    },
    { id: 29, icon: Music, title: "Music", description: "Live music sessions" },
    {
      id: 30,
      icon: Camera,
      title: "Photography",
      description: "Capture your moments",
    },
    {
      id: 31,
      icon: Heart,
      title: "Relaxation",
      description: "Relax and unwind",
    },
    { id: 32, icon: Film, title: "Movies", description: "Enjoy movie nights" },
    {
      id: 33,
      icon: Mail,
      title: "Packaged Drinking Water 4",
      description: "Complimentary",
    },
    {
      id: 34,
      icon: Bell,
      title: "Concierge and Housekeeping Staff 4",
      description: "Professional, highly trained & experienced",
    },
    {
      id: 35,
      icon: Star,
      title: "Mini-Library 4",
      description: "Fiction, Biography, Children, Fantasy",
    },
    {
      id: 36,
      icon: Check,
      title: "Indoor Activities 4",
      description: "Carrom, Chess, UNO, Jenga, Scrabble, Monopoly",
    },
  ],
  [
    { id: 37, icon: Home, title: "Barbeque 5", description: "Outdoor BBQ fun" },
    {
      id: 38,
      icon: User,
      title: "Sheesha 5",
      description: "Relax with Sheesha",
    },
    {
      id: 39,
      icon: Settings,
      title: "Bonfire 5",
      description: "Enjoy a cozy bonfire",
    },
    {
      id: 40,
      icon: Mail,
      title: "Packaged Drinking Water 5",
      description: "Complimentary",
    },
    {
      id: 41,
      icon: Bell,
      title: "Concierge and Housekeeping Staff 5",
      description: "Professional, highly trained & experienced",
    },
    {
      id: 42,
      icon: Star,
      title: "Mini-Library 5",
      description: "Fiction, Biography, Children, Fantasy",
    },
    {
      id: 43,
      icon: Check,
      title: "Indoor Activities 5",
      description: "Carrom, Chess, UNO, Jenga, Scrabble, Monopoly",
    },
    {
      id: 44,
      icon: AlertCircle,
      title: "Outdoor Sports 5",
      description: "Cricket Kit, Badminton Set, Football",
    },
    {
      id: 45,
      icon: Calendar,
      title: "Mocktails on arrival 5",
      description: "Piña Colada, Mojito, Blue Curaçao",
    },
  ],
];
