import {
  FaBed,
  FaCouch,
  FaUsers,
  FaSwimmingPool,
  GiMeal,
  FaMusic,
  FaWifi,
  FaTv,
  FaBlog,
  MdOutlineNoMeals,
  MdNoMeals,
} from "react-icons/fa";
import {
  Home,
  User,
  Settings,
  Mail,
  Bell,
  Star,
  Check,
  AlertCircle,
  Calendar,
  Coffee,
  Music,
  Camera,
  Heart,
  Film,
  UtensilsCrossed,
} from "lucide-react";

export const carouselContent = [
  [
    {
      id: 1,
      icon: FaBed,
      title: "6 Master Bedrooms",
      description: "Air conditioned with an attached balcony",
    },
    {
      id: 2,
      icon: FaCouch,
      title: "Spacious Living Room",
      description: "Sofa Set | Dining Area | Fully Air Conditioned",
    },
    {
      id: 3,
      icon: FaUsers,
      title: "25-30 guests",
      description: "Suitable for family, friends and corporate getaways",
    },
    {
      id: 4,
      icon: FaSwimmingPool,
      title: "Private Swimming Pool",
      description:
        "Full size | Waterfall | Patio loungers | Underwater LED Lighting",
    },
    {
      id: 5,
      icon: UtensilsCrossed,
      title: "Meals",
      description:
        "Vegetarian | Non-Vegetarian | Jain Meal Plan (Breakfast, Lunch, High Tea, Dinner) ",
    },
    {
      id: 6,
      icon: FaMusic,
      title: "Music System",
      description: "Bluetooth, USB & AUX connectivity | Karaoke",
    },
    {
      id: 7,
      icon: FaWifi,
      title: "High-Speed WiFi",
      description: "Speed upto 30 MBPS",
    },
    {
      id: 8,
      icon: FaTv,
      title: "Smart Television",
      description: "Full HD 50 inch LED",
    },
    {
      id: 9,
      icon: FaBlog,
      title: "Online Streaming",
      description: "Netflix | Disney + Hotstar | Amazon Prime",
    },
  ],
  [
    { id: 10, icon: FaDrumstickBite, title: "Barbeque 2", description: "Outdoor BBQ fun" },
    {
      id: 11,
      icon: User,
      title: "Sheesha 2",
      description: "Relax with Sheesha",
    },
    {
      id: 12,
      icon: FaFreeCodeCamp,
      title: "Bonfire 2",
      description: "Enjoy a cozy bonfire",
    },
    {
      id: 13,
      icon: Mail,
      title: "Packaged Drinking Water 2",
      description: "Complimentary",
    },
    {
      id: 14,
      icon: Bell,
      title: "Concierge and Housekeeping Staff 2",
      description: "Professional, highly trained & experienced",
    },
    {
      id: 15,
      icon: FaBookReader,
      title: "Mini-Library 2",
      description: "Fiction, Biography, Children, Fantasy",
    },
    {
      id: 16,
      icon: FaChessKing,
      title: "Indoor Activities 2",
      description: "Carrom, Chess, UNO, Jenga, Scrabble, Monopoly",
    },
    {
      id: 17,
      icon: FaFutbol,
      title: "Outdoor Sports 2",
      description: "Cricket Kit, Badminton Set, Football",
    },
    {
      id: 18,
      icon: FaCocktail,
      title: "Mocktails on arrival 2",
      description: "Piña Colada, Mojito, Blue Curaçao",
    },
  ],
  [
    { id: 19, icon: FaBuffer, title: "High Quality Mattresses,Towels and Linens", description: "Comfortable and cozy stay" },
    {
      id: 20,
      icon: FaParking,
      title: "Secure Car Park",
      description: "Under CCTV Surveillance",
    },
    {
      id: 21,
      icon: FaUserLock,
      title: "24X7 Security",
      description: "CCTV Cameras | Security Guard | Fire Extinguishers",
    },
    {
      id: 22,
      icon: FaPhoneVolume,
      title: "Intercom",
      description: "Room to Room | Room to Housekeeping",
    },
    {
      id: 23,
      icon: FaBuilding,
      title: "Terrace",
      description: "Large sit out area on Level 1",
    },
    {
      id: 24,
      icon: FaRestroom,
      title: "8 Washrooms",
      description: "Modern Fittings and Amenities",
    },
    {
      id: 25,
      icon: FaPaw,
      title: "Pet Friendly",
      description: "We love out Four-Legged friends",
    },
    {
      id: 26,
      icon: FaBan,
      title: "Swimming pool timings",
      description: "No restriction",
    },
    {
      id: 27,
      icon: FaBirthdayCake,
      title: "Events, Functions and Parties",
      description: "Planning | Organizing | Execution",
    },
  ],
  [
    {
      id: 28,
      icon: FaUtensils,
      title: "Fully stocked kitchen",
      description: "Refrigerator | Microwave | Cookware | Gas Stove & Cylinder",
    },
    { id: 29, icon: FaToiletPaper, title: "Toiletries", description: "Ignis Range by Five Elements" },
    {
      id: 30,
      icon: FaPersonBooth,
      title: "Wardrobes and garment hangers",
      description: "In all bedrooms",
    },
    {
      id: 31,
      icon: FaFirstAid,
      title: "First Aid Kit",
      description: "Emergency Supplies",
    },
    { id: 32, icon: FaBuffer, title: "Extra Mattresses", description: "For additional guests" },
    {
      id: 33,
      icon: FaUserMd,
      title: "Doctor on Call",
      description: "24X7",
    },
    {
      id: 34,
      icon:FaCar,
      title: "Airport Transfers4",
      description: "Pickup and drop off services",
    },
    {
      id: 35,
      icon: FaHandshake,
      title: "24X7 G",
      description: "Fiction, Biography, Children, Fantasy",
    },
    {
      id: 36,
      icon: Check,
      title: "Indoor Activities 4",
      description: "Carrom, Chess, UNO, Jenga, Scrabble, Monopoly",
    },
  ],
  [
    { id: 37, icon: Home, title: "Barbeque 5", description: "Outdoor BBQ fun" },
    {
      id: 38,
      icon: User,
      title: "Sheesha 5",
      description: "Relax with Sheesha",
    },
    {
      id: 39,
      icon: Settings,
      title: "Bonfire 5",
      description: "Enjoy a cozy bonfire",
    },
    {
      id: 40,
      icon: Mail,
      title: "Packaged Drinking Water 5",
      description: "Complimentary",
    },
    {
      id: 41,
      icon: Bell,
      title: "Concierge and Housekeeping Staff 5",
      description: "Professional, highly trained & experienced",
    },
    {
      id: 42,
      icon: Star,
      title: "Mini-Library 5",
      description: "Fiction, Biography, Children, Fantasy",
    },
    {
      id: 43,
      icon: Check,
      title: "Indoor Activities 5",
      description: "Carrom, Chess, UNO, Jenga, Scrabble, Monopoly",
    },
    {
      id: 44,
      icon: AlertCircle,
      title: "Outdoor Sports 5",
      description: "Cricket Kit, Badminton Set, Football",
    },
    {
      id: 45,
      icon: Calendar,
      title: "Mocktails on arrival 5",
      description: "Piña Colada, Mojito, Blue Curaçao",
    },
  ],
];
